input_datetime:
  zirkulation_last_run:
    name: Zirkulation letzte Ausführung
    has_date: true
    has_time: true

input_number:
  zirkulation_laufzeit_sekunden:
    name: Zirkulation Standard-Laufzeit
    min: 60
    max: 300
    step: 10
    initial: 150
    unit_of_measurement: "s"
    icon: mdi:timer

input_boolean:
  zirkulation_manuell_gesperrt:
    name: Zirkulation manuell gesperrt
    initial: false
    icon: mdi:lock

script:
  zirkulation_pumpe_laufen_lassen:
    alias: Zirkulation Pumpe laufen lassen
    mode: restart
    fields:
      sekunden:
        description: Laufzeit in Sekunden
        example: 150
    sequence:
      # Prüfe ob Pumpe gesperrt ist
      - condition: state
        entity_id: input_boolean.zirkulation_manuell_gesperrt
        state: "off"
      
      # Prüfe Mindestpause (15 Minuten)
      - condition: template
        value_template: >-
          {% set last = states('input_datetime.zirkulation_last_run') %}
          {% if last in ['unknown', 'unavailable', ''] %}
            true
          {% else %}
            {{ (now() - as_datetime(last)).total_seconds() > 900 }}
          {% endif %}
      
      # Setze Timestamp VOR dem Start (verhindert Race Conditions)
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.zirkulation_last_run
        data:
          datetime: "{{ now().isoformat() }}"
      
      # Pumpe starten
      - service: switch.turn_on
        target:
          entity_id: switch.keller_zirkulationspumpe
      
      # Warten
      - delay:
          seconds: "{{ sekunden | int(150) }}"
      
      # Pumpe stoppen
      - service: switch.turn_off
        target:
          entity_id: switch.keller_zirkulationspumpe

automation:
  # === MORGENS (Hauptzeit) ===
  - id: zirkulation_morgens_og_flur_praesenz
    alias: Zirkulation morgens OG Flur bei Präsenz
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.prasenz_flur_og
        to: "on"
    condition:
      - condition: time
        after: "05:00:00"
        before: "09:00:00"
    action:
      - service: script.zirkulation_pumpe_laufen_lassen
        data:
          sekunden: "{{ states('input_number.zirkulation_laufzeit_sekunden') | int(150) }}"

  - id: zirkulation_morgens_gaeste_wc_praesenz
    alias: Zirkulation morgens Gäste WC bei Präsenz
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.prasenz_gaste_wc
        to: "on"
    condition:
      - condition: time
        after: "05:00:00"
        before: "09:00:00"
    action:
      - service: script.zirkulation_pumpe_laufen_lassen
        data:
          sekunden: "{{ states('input_number.zirkulation_laufzeit_sekunden') | int(150) }}"

  # === TAGSÜBER (Reduziert) ===
  - id: zirkulation_tagsueber_og_flur_praesenz
    alias: Zirkulation tagsüber OG Flur bei Präsenz (reduziert)
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.prasenz_flur_og
        to: "on"
        for:
          seconds: 5
    condition:
      - condition: time
        after: "09:00:00"
        before: "21:00:00"
    action:
      - service: script.zirkulation_pumpe_laufen_lassen
        data:
          sekunden: "{{ (states('input_number.zirkulation_laufzeit_sekunden') | int(150) * 0.8) | int }}"

  - id: zirkulation_tagsueber_gaeste_wc_praesenz
    alias: Zirkulation tagsüber Gäste WC bei Präsenz (reduziert)
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.prasenz_gaste_wc
        to: "on"
        for:
          seconds: 5
    condition:
      - condition: time
        after: "09:00:00"
        before: "21:00:00"
    action:
      - service: script.zirkulation_pumpe_laufen_lassen
        data:
          sekunden: "{{ (states('input_number.zirkulation_laufzeit_sekunden') | int(150) * 0.8) | int }}"

  # === BENACHRICHTIGUNGEN ===
  - id: zirkulation_pumpe_info
    alias: Zirkulation Pumpe Info
    mode: queued
    trigger:
      - platform: state
        entity_id: switch.keller_zirkulationspumpe
        to: "on"
    action:
      - service: logbook.log
        data:
          name: Zirkulationspumpe
          message: >-
            Pumpe gestartet für {{ states('input_number.zirkulation_laufzeit_sekunden') }}s
            (Trigger: {{ trigger.to_state.context.parent_id | default('Manuell') }})

sensor:
  - platform: history_stats
    name: Zirkulationspumpe Laufzeit heute
    entity_id: switch.keller_zirkulationspumpe
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Zirkulationspumpe Starts heute
    entity_id: switch.keller_zirkulationspumpe
    state: "on"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: template
    sensors:
      zirkulationspumpe_energie_heute:
        friendly_name: "Zirkulationspumpe Energie heute"
        unit_of_measurement: "kWh"
        value_template: >-
          {{ (states('sensor.zirkulationspumpe_laufzeit_heute') | float(0) * 0.05) | round(2) }}
        icon_template: mdi:flash